[package]
name = "git_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = { workspace = true }
clap = { version = "4.5.35", features = ["derive"] }
git_core = { path = "../git_core" }
itertools = { workspace = true }
log = "0.4.27"
simple-logging = "2.0.2"
